export { 
    POSTS_FETCH_START,
    POSTS_FETCH_COMPLETE,
    POSTS_FETCH_FAILURE,

    ADD_POST_START,
    ADD_POST_COMPLETE,
    ADD_POST_FAILURE,

    POST_GET_START,
    POST_GET_COMPLETE,
    POST_GET_FAILURE,

    POST_EDIT_START,
    POST_EDIT_COMPLETE,
    POST_EDIT_FAILURE,

    DELETE_POST_START,
    DELETE_POST_COMPLETE,
    DELETE_POST_FAILURE,

    getPosts,
    addNewPost,
    getPost,
    editPost,
    deletePost
} from './postsActions';