export const FETCHING_POSTS = "FETCHING_POSTS";
export const ADDING_POST = "ADDING_POST";
export const DELETING_POST = "DELETING_POST";
export const EDITING_POST = "EDITING_POST";

export const SUCCESS_POSTS = "SUCCESS_POSTS";
export const ERROR_POSTS = "ERROR_POSTS";
